services:
  # LLM投資アイデア検証ツールWebアプリ
  - type: web
    name: stock-simulator-web
    env: docker
    dockerfilePath: Dockerfile
    region: singapore
    plan: free
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stock-simulator-db
          property: connectionString
      - key: DEBUG
        value: "false"
      - key: PORT
        value: "8000"
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: stock-simulator-db
    region: singapore
    plan: free
    postgresMajorVersion: "15"
    ipAllowList: []
